cc_library(
    name = 'core',
    includes = ['.'],
    deps = [
        '@asio_repo//:asio',
    ],
    visibility = ['//visibility:public'],
    srcs = glob(['core/*.cpp']),
    hdrs = glob(['core/*.hpp']),
),

